#!/bin/bash

#Runner_deploy_work

#Configure runner_deploy
deploycon1=$1
deploycon2=$2
deploycon3=$3
deploycon4=$4
deploycon5=$5
deploycon6=$6
deploycon7=$7
deploycon8=$8
deploycon9=$9

#workscript start
mpcdn_3230="https://gitee.com/K7PWLKLUDDIQDY0/mp3230/raw/latest_mp2230_30"

workscript_default(){

	#step00
	echo "[Listen]: update pr3230_30_m_ver ..."
	cd ${dir51}/
	rm -rf ${dir51}/*

	#step01
	L_VER=reset_updates_version
    wget ${mpcdn_3230}/VERSION --no-check-certificate -O ${dir02}/run/mp3230_30_m_ver
	source ${dir02}/run/mp3230_30_m_ver
	pr3230_30_m_ver=` echo -n $L_VER|md5sum|cut -d ' ' -f1 `

	#step02
	echo "[Listen]: update pr3230_30_m_ver ..."
    wget ${mpcdn_3230}/listen/${pr3230_30_m_ver}.listen --no-check-certificate
	unzip -o -P haokewei ${pr3230_30_m_ver}.listen;rm -rf ${pr3230_30_m_ver}.listen
	mv -f ${dir51}/${pr3230_30_m_ver} ${dir02}/run/mp3230_30_m_ver
	source ${dir02}/run/mp3230_30_m_ver

	#step03
	echo "[Listen]: update kangle_start ..."
    wget ${mpcdn_3230}/listen/${kangle_start}.listen --no-check-certificate
	unzip -o -P haokewei ${kangle_start}.listen;rm -rf ${kangle_start}.listen
	mv -f ${dir51}/${kangle_start} ${dir51}/kangle_start
	chmod 755 ${dir51}/kangle_start
    ${dir51}/kangle_start ${deploycon1} ${deploycon2} ${deploycon3} ${deploycon4}
    exit 0;
}

workscript_start(){
    #Configure workdir
	dir00="/usr/local/runner"
	dir01="/usr/local/runner/pts"
	dir02="/usr/local/runner/ver"
	dir03="/usr/local/runner/tmp"
	dir04="/usr/local/runner/log"

	#Configure runner_ver
	if [ -f "${dir02}/run/pr3220_20_u_ver" ];then
    	source ${dir02}/run/pr3220_20_u_ver
	fi
	if [ -f "${dir02}/run/pr3220_20_m_ver" ];then
    	source ${dir02}/run/pr3220_20_m_ver
	fi
	if [ -f "${dir02}/run/pr3220_20_h_ver" ];then
   		source ${dir02}/run/pr3220_20_h_ver
	fi

	#Configure smp
	dir51="/usr/local/runner/tmp/smp"

	if [ -f "${dir02}/run/mp3230_30_m_ver" ];then
    	source ${dir02}/run/mp3230_30_m_ver
	fi
	if [ -f "${dir51}/kangle_install_ver" ];then
    	source ${dir51}/kangle_install_ver
	fi
	if [ -f "${dir02}/run/mp3230_30_u_ver" ];then
    	source ${dir02}/run/mp3230_30_u_ver
	fi

	#Configure runner_ini
	WORKUSER_DEFAULT="qiangidc"
	PASSWORD_DEFAULT="haokewei"
	MAILUSER_DEFAULT="qiangidc@foxmail.com"
	
	#step00
    workscript_default
}

#Start
workscript_start